anime_info = [
    {'Name': 'Fullmetal Alchemist: Brotherhood', 'Media Type': 'TV', 'Episodes': '64', 'Studio': ['Bones'], 'Start Year': '2009', 'End Year': '2010', 'Ongoing': False, 'Release Season': 'Spring', 'Rating': '4.571', 'Rank': '4', 'Members': '215284', 'Genre': ['Action', 'Adventure', 'Drama', 'Fantasy', 'Mystery', 'Shounen', 'Conspiracy', 'Death of a Loved One', 'Military', 'Siblings', 'Based on a Manga'], 'Creator': 'Hiromu ARAKAWA'},
    {'Name': 'Fruits Basket the Final Season', 'Media Type': 'TV', 'Episodes': '13', 'Studio': ['TMS Entertainment', '8 Pan'], 'Start Year': '2021', 'End Year': None, 'Ongoing': False, 'Release Season': 'Spring', 'Rating': '4.575', 'Rank': '2', 'Members': '31719', 'Genre': ['Drama', 'Fantasy', 'Romance', 'Shoujo', 'Animal Transformation', 'Contemporary Fantasy', 'Curse', 'Dysfunctional Families', 'Mental Illness', 'Orphans', 'Zodiac', 'Based on a Manga'], 'Creator': 'Natsuki TAKAYA'},
    {'Name': 'Bleach: Thousand-Year Blood War', 'Media Type': 'TV', 'Episodes': '13', 'Studio': ['Pierrot'], 'Start Year': '2022', 'End Year': None, 'Ongoing': False, 'Release Season': 'Fall', 'Rating': '4.547', 'Rank': '7', 'Members': '16485', 'Genre': ['Action', 'Comedy', 'Drama', 'Shounen', 'Afterlife', 'Ghosts', 'Shinigami', 'Supernatural', 'War', 'Based on a Manga'], 'Creator': 'Tite KUBO'},
    {'Name': 'Attack on Titan The Final Season: The Final Chapters', 'Media Type': 'TV Special', 'Episodes': '1', 'Studio': ['MAPPA'], 'Start Year': '2023', 'End Year': None, 'Ongoing': True, 'Release Season': None, 'Rating': '4.645', 'Rank': '1', 'Members': '13292', 'Genre': ['Action', 'Drama', 'Fantasy', 'Shounen', 'Dark Fantasy', 'Military', 'War', 'Based on a Manga'], 'Creator': 'Hajime ISAYAMA'},
    {'Name': 'Yawaraka Atom', 'Media Type': 'Web', 'Episodes': '7', 'Studio': ['Fanworks'], 'Start Year': '2007', 'End Year': '2008', 'Ongoing': False, 'Release Season': None, 'Rating': None, 'Rank': None, 'Members': '54', 'Genre': ['Comedy', 'Parody', 'Short Episodes'], 'Creator': 'Rareko'},
    {'Name': 'EggRoy', 'Media Type': 'TV', 'Episodes': '104', 'Studio': [''], 'Start Year': '2019', 'End Year': None, 'Ongoing': False, 'Release Season': None, 'Rating': None, 'Rank': None, 'Members': '48', 'Genre': ['Anthropomorphic', 'Family Friendly', 'Food Protagonists', 'Korean Animation', 'Non-Human Protagonists', 'Short Episodes'], 'Creator': None},
    {'Name': 'Hizukuri', 'Media Type': 'Other', 'Episodes': None, 'Studio': [''], 'Start Year': None, 'End Year': None, 'Ongoing': False, 'Release Season': None, 'Rating': None, 'Rank': None, 'Members': '607', 'Genre': ['Adventure', 'Sci Fi', 'Original Work'], 'Creator': 'Naoki MATSUURA'}
]
